INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'Srikanth', 'Learn AWS CDA', SYSDATE, 0);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'Srikanth', 'Learn Java', SYSDATE, 0);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'Srikanth', 'Learn SpringBoot', SYSDATE, 0);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'Srikanth', 'Learn ReactJS', SYSDATE, 0);
